"""Add telegram_id to users photo url

Revision ID: b69bb314922a
Revises: 6d65a04bd0bf
Create Date: 2025-06-18 10:50:03.903787

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b69bb314922a"
down_revision: Union[str, None] = "6d65a04bd0bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("photo_url", sa.String(), nullable=True))
    op.drop_column("users", "photo_ur")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "photo_ur", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("users", "photo_url")
    # ### end Alembic commands ###
