"""initial users

Revision ID: 97a308648817
Revises: f0d395323d8b
Create Date: 2025-06-09 23:05:05.206169

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "97a308648817"
down_revision: Union[str, None] = "f0d395323d8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("telegram_id", sa.Integer(), nullable=False)
    )
    op.add_column("users", sa.Column("first_name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("last_name", sa.String(), nullable=True))
    op.add_column("users", sa.Column("photo_ur", sa.String(), nullable=True))
    op.alter_column(
        "users", "username", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_constraint("uq_users_username", "users", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_users_username", "users", ["username"])
    op.alter_column(
        "users", "username", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_column("users", "photo_ur")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_column("users", "telegram_id")
    # ### end Alembic commands ###
