version: '3.8'

services:
  db:
    image: postgres:15
    container_name: em_test_db
    restart: always
    ports:
      - "5441:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: shop_pass123
      POSTGRES_DB: test_shop

volumes:
  postgres_data:
