name: Deploy to Server (back-prod)

on:
  push:
    branches:
      - back-prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            set -x  # Показывать каждую команду перед выполнением
            cd ${{ secrets.DEPLOY_DIR }} || exit 1
            git pull origin back-prod || exit 1
            docker-compose down || docker compose down || exit 1
            docker-compose up -d --build || docker compose up -d --build || exit 1
            set +x
          EOF
